services:
    rubencm.customregistrationagreement.listener:
        class: rubencm\customregistrationagreement\event\listener
        arguments:
            - '@config'
            - '@config_text'
            - '@template'
        tags:
            - { name: event.listener }
